# Development override configuration
# This file is automatically loaded by docker-compose for development
version: '3.8'

services:
  novita-gpu-api:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      # Development logs (use local directory)
      - ./logs:/app/logs
    # Remove read-only restriction for development
    read_only: false
    # Remove tmpfs restrictions for development
    tmpfs: []
    # Remove security restrictions for easier debugging
    security_opt: []
    # Faster restart for development
    restart: "no"
    # Development resource limits (more generous)
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 256M
          cpus: '0.25'